services:
  backend:
    build: ./back
    command: sh -c "npm run build && npm run prod"
    expose:
      - 4000
    environment:
      - DATA_FIXTURE=$DATA_FIXTURE
      - DATA_FIXTURE_CATEGORIES=$DATA_FIXTURE_CATEGORIES
      - DATA_FIXTURE_PRODUCTS=$DATA_FIXTURE_PRODUCTS
    volumes:
      - ./back/src:/app/src
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s

  frontend:
    build: ./front
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build:
