services:
  backend:
    build: ./back
    env_file:
      - vars.env
    environment:
      - DATA_FIXTURE_CATEGORIES=$DATA_FIXTURE_CATEGORIES
      - DATA_FIXTURE_PRODUCTS=$DATA_FIXTURE_PRODUCTS
      - DATA_FIXTURE_USERS=$DATA_FIXTURE_USERS
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src
    healthcheck:
      test: "curl --fail --request GET --header 'content-type: application/json' --url 'http://localhost:4000' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s

  frontend:
    build: ./front
    env_file:
      - vars.env
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./front/src:/app/src
    depends_on:
      backend:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
