services:
  backend:
    build: ./back
    env_file:
      - vars.env
    environment:
      - DATA_FIXTURE=$DATA_FIXTURE
      - DATA_FIXTURE_CATEGORIES=$DATA_FIXTURE_CATEGORIES
      - DATA_FIXTURE_PRODUCTS=$DATA_FIXTURE_PRODUCTS
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s

  frontend:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
    command: npm run test

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
