name: 🧪- tests e2e

on:
  pull_request:
    branches:
      - dev

jobs:
  tests-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          JWT_SECRET_KEY: testtesttest
          POSTGRES_PASSWORD: testtesttest
          REFRESH_JWT_SECRET_KEY: testtesttest
        run: |
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> vars.env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> vars.env
          echo "REFRESH_JWT_SECRET_KEY=${REFRESH_JWT_SECRET_KEY}" >> vars.env

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.e2e.yml up --build --exit-code-from e2e

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./e2e/test-results

      - name: Check exit code and fail if tests failed
        run: exit $(docker-compose -f path/to/your/docker-compose.yml ps -q e2e | xargs docker inspect --format '{{ .State.ExitCode }}')
