name: 🧪- tests frontend

on:
  push
  # pull_request:
  #   branches:
  #     - dev

jobs:
  tests-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          JWT_SECRET_KEY: testtesttest
          POSTGRES_PASSWORD: testtesttest
          REFRESH_JWT_SECRET_KEY: testtesttest
        run: |
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> vars.env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> vars.env
          echo "REFRESH_JWT_SECRET_KEY=${REFRESH_JWT_SECRET_KEY}" >> vars.env

      - name: Start Docker Compose
        run: |
          DATA_FIXTURE_CATEGORIES=true DATA_FIXTURE_PRODUCTS=true DATA_FIXTURE_USERS=true docker compose up --build -d

      - name: Wait for frontend container to be healthy
        run: |
          until docker compose logs frontend 2>&1 | grep -q "No issues found."; do sleep 5; done

      - name: Run npm test in frontend container
        run: |
          docker compose exec -T frontend npm run testCI
