name: 🧪-tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up environment variables
        env:
          JWT_SECRET_KEY: testtesttest
          POSTGRES_PASSWORD: testtesttest
        run: |
          echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" >> vars.env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> vars.env

      - name: Start Docker Compose
        run: |
          DATA_FIXTURE_CATEGORIES=true DATA_FIXTURE_PRODUCTS=true docker compose up --build -d

      - name: Wait for frontend container to be healthy
        run: |
          FRONTEND_CONTAINER=$(docker-compose ps -q frontend)
          while [ "$(docker inspect -f '{{.State.Health.Status}}' $FRONTEND_CONTAINER)" != "healthy" ]; do
            sleep 5
          done

      - name: Run npm test in frontend container
        run: |
          docker exec 2023-03-wns-keller-groupe4-frontend-1 npm run test